### ISSUE TITLE
26.0.12 - 26.0.17 breaks yarn workspace

### ISSUE THREAD

**Issue by itx-niklas-baugatz** [electron-userland/electron-builder#9187]
Hey there, i have a problem with my yarn workspace.

🧩 Project Setup
Stack: Angular + Electron (shared package.json)
electron-builder: upgraded from v26.0.11 to v26.0.12 (26.0.17 has the same issue)
yarn 1.22.22

🐞 Problem
After upgrading to v26.0.12:
node_modules is not copied into the .asar bundle.

The build completes without errors, but the installed app fails at runtime with:

Cannot find module '<first-required-dependency>'

Build debug output shows:

collected node modules  nodeModules=[]
When using Yarn, nodeModules is empty, but building with npm or pnpm works as expected (logged full array of deps). Switching to pnpm resolves the issue. Specifying yarn as packagemanager, causes the build to fail.

🔗 Related Issues
https://github.com/electron-userland/electron-builder/issues/9169

✅ Expected Behavior
Building under Yarn should:
Copy node_modules into .asar
Yield a working app with no runtime missing-module errors

Run yarn electron-builder
Build succeeds

Debuglogs show collected node modules nodeModules=[]
Resulting .asar lacks dependencies
App crashes with “Cannot find module”

Switch to pnpm or npm, rebuild → Everything works

I can't switch back to 26.0.11 because 26.0.12 fixes a signing issue.

**Comment by beyondkmp** [comment]
could you please provide a mini reproduce demo?

**Comment by dosprn** [comment]
Look at #9161 also. I suspect the same problem is here.

**Comment by itx-niklas-baugatz** [comment]
thanks for the quick response, i created a demo
https://github.com/itx-niklas-baugatz/electron-builder-issue-9187

onNodeModuleFile() {return true} is a workaround on windows and linux, but does not work on mac

everything else seems works fine, when written in the files[] property, its only the node_modules

**Comment by itx-niklas-baugatz** [comment]
Do you think there is a way to fix this or a workaround for the time, so i could still use yarn?
I switched my project to npm but it brings other problems, like i need to manually install optional dependencies (dmg-license) on macos to build, which wasn't an issue with yarn.

**Comment by beyondkmp** [comment]
@itx-niklas-baugatz Could you try the 26.0.18?

**Comment by beyondkmp** [comment]
This is caused by https://github.com/electron-userland/electron-builder/pull/9026.

<img width="2003" height="127" alt="Image" src="https://github.com/user-attachments/assets/f06a9b8a-2125-4e21-ad5e-bcbd3f9dda0d" />

**Comment by beyondkmp** [comment]
@itx-niklas-baugatz 

It's just a one-line code change — you can modify it locally to test. Replace the content of this file(node_modules/app-builder-lib/out/node-module-collector/yarnNodeModulesCollector.js) with the following and see how it works:

```javascript

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.YarnNodeModulesCollector = void 0;
const npmNodeModulesCollector_1 = require("./npmNodeModulesCollector");
const packageManager_1 = require("./packageManager");
class YarnNodeModulesCollector extends npmNodeModulesCollector_1.NpmNodeModulesCollector {
    constructor(rootDir) {
        super(rootDir);
        // note: do not override instance-var `pmCommand`. We explicitly use npm for the json payload
        // yarn list cannot get the detailed dependencies path info, so we use npm to get the json payload
        this.installOptions = { manager: packageManager_1.PM.NPM, lockfile: "yarn.lock" };
    }
}
exports.YarnNodeModulesCollector = YarnNodeModulesCollector;
//# sourceMappingURL=yarnNodeModulesCollector.js.map
```
