### ISSUE TITLE
"Cannot find module" errors after upgrade to electron-builder 26

### ISSUE THREAD

**Issue by KillerCodeMonkey** [electron-userland/electron-builder#9006]
I am using the node-module "form-data" in a project and after upgrade to electron builder from v25 to v26 i get the following error after starting the final app package.

```ts
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'delayed-stream'
Require stack:
- /tmp/.mount_APP Co8bvpMS/resources/app.asar/node_modules/combined-stream/lib/combined_stream.js
- /tmp/.mount_APP Co8bvpMS/resources/app.asar/node_modules/form-data/lib/form_data.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:129170)
    at Module._load (node:internal/modules/cjs/loader:1062:27)
    at c._load (node:electron/js2c/node_init:2:18008)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:227:24)
    at Module.require (node:internal/modules/cjs/loader:1318:12)
    at require (node:internal/modules/helpers:136:16)
```

Seems like not all nested dependencies are correctly bundled.

https://github.com/KillerCodeMonkey/electron-builder-26-modules-not-found/tree/main

**Comment by Nantris** [comment]
Any particular platform? Looks like Linux?

**Comment by KillerCodeMonkey** [comment]
I just tested it on Ubuntu 24.04 and electron v35.

Since all my mac/win mates were already in their after hours. I could not verify it on other platform. 


Am 2. April 2025 21:08:04 MESZ schrieb Nantris ***@***.***>:

**Comment by beyondkmp** [comment]
@KillerCodeMonkey 
Test directly using the `form-data` library; I am unable to reproduce the issue on my end. Could you help provide a minimal reproducible demo code?

**Comment by KillerCodeMonkey** [comment]
Strange if i build it locally it is working, but when building via ci (github actions) those problems are popping up.

**Comment by KillerCodeMonkey** [comment]
@beyondkmp we are building the app in the ci like this:

NODE_ENV=production
NPM_CONFIG_PRODUCTION=false

and then `npm ci` instead of `npm i`

if you set both envs locally i can reproduce the error, even formData is a production dep

**Comment by KillerCodeMonkey** [comment]
See: https://github.com/KillerCodeMonkey/electron-builder-26-modules-not-found/tree/main

**Comment by panther7** [comment]
We have similar issue with `dependency path is undefined`, becase project has `node_modules` in root folder, but "build" folder is without `node_modules`.
Posible sotution is define path for node_modules, like this https://www.electron.build/app-builder-lib.interface.metadatadirectories

Example:
```
.
├── node_modules
└── dist
    └── app.html
```

Works perfectly in electron-builder 25.

**Comment by beyondkmp** [comment]
Released [v26.0.13](https://github.com/electron-userland/electron-builder/releases/tag/v26.0.13)

**Comment by KillerCodeMonkey** [comment]
@beyondkmp looks good. Thank you very much!
