### ISSUE TITLE
pnpm cannot import @electron/osx-sign/dist/cjs/util-identities

### ISSUE THREAD

**Issue by Sytten** [electron-userland/electron-builder#9816]
Due to the changes to dynamic import introduced in https://github.com/electron-userland/electron-builder/pull/9792, it seems to break with pnpm:

```
 ⨯ Cannot find module '/Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/@electron/osx-sign/dist/cjs/util-identities' imported from /Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/app-builder-lib/helpers/dynamic-import.js
Did you mean to import "@electron/osx-sign/dist/cjs/util-identities.js"?  failedTask=build stackTrace=Error: Cannot find module '/Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/@electron/osx-sign/dist/cjs/util-identities' imported from /Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/app-builder-lib/helpers/dynamic-import.js
Did you mean to import "@electron/osx-sign/dist/cjs/util-identities.js"?
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:861:10)
    at defaultResolve (node:internal/modules/esm/resolve:985:11)
    at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:747:20)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:724:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:320:38)
    at onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:680:36)
    at TracingChannel.tracePromise (node:diagnostics_channel:350:14)
    at ModuleLoader.import (node:internal/modules/esm/loader:679:21)
    at defaultImportModuleDynamicallyForScript (node:internal/modules/esm/utils:235:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:257:12)
    at Object.dynamicImport (/Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/app-builder-lib/helpers/dynamic-import.js:6:78)
    at dynamicImport (/Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/app-builder-lib/src/util/dynamicImport.ts:10:18)
    at MacTargetHelper.findSigningIdentity (/Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/app-builder-lib/src/mac/MacTargetHelper.ts:61:64)
    at MacPackager.sign (/Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/app-builder-lib/src/macPackager.ts:385:22)
    at /Users/sytten/Projects/MYPROJECT/node_modules/.pnpm/app-builder-lib@26.13.0_dmg-builder@26.13.0_electron-builder-squirrel-windows@26.13.0/node_modules/app-builder-lib/src/macPackager.ts:541:13
```

It looks like an issue of a missing `.js` in the import name, would that be due to the `moduleResolution` of our tsconfig?

**Comment by mmaietta** [comment]
Thanks for the report @Sytten! Pushed up #9817. Should get a release out shortly

**Comment by Sytten** [comment]
Thanks much appreciated! I am wondering if you plan on dropping CJS and just go directly ESM since electron is moving to it anyway. That would simplify the code a whole lot.

**Comment by mmaietta** [comment]
That's my intention for v27 actually in https://github.com/electron-userland/electron-builder/pull/9544. But I'm now debating on seeing if I can do a dual CJS/ESM package publish to make a migration pathway easier (and avoid having to manage 2 separate release branches)

**Comment by Sytten** [comment]
Honestly ESM is supported everywhere now, I have stopped using CJS years ago but for you
