### ISSUE TITLE
local dependencies (file:path instead of version) are not included in app.asar

### ISSUE THREAD

**Issue by flexopticalHenno** [electron-userland/electron-builder#8401]
* **Electron-Builder Version**: 25.0.0, 25.0.1, 25.0.2

* **Node Version**: 20.16.0, 18.20.4

* **Electron Version**: 31.3.1
* **Electron Type (current, beta, nightly)**: current

* **Electron-Updater Version**: 6.3.2, 6.2.1

* **Target**: Win32 x64 NSIS

When packing the app with electron-builder, a local dependency (version is `file:path/to/lib`) is not included in `app.asar/node_modules`. This was working with electron-builder 24.13.3

When installing the local dependency, npm creates a symbolic link in the `node_modules` folder that points to the source of the dependency on the local file system. Electron-builder 24.13.3 created a copy of that folder in `app.asar`, but with electron-builder 25 it is missing. Starting the app will show an error dialog stating "Uncaught Exception: Error: Cannot find module 'name-of-local-dependency'".

**Comment by beyondkmp** [comment]
I wrote a small demo myself and couldn't reproduce the issue you mentioned.

[hello.zip](https://github.com/user-attachments/files/16508485/hello.zip)


Could you provide a demo code that reproduces the problem?

**Comment by flexopticalHenno** [comment]
I reproduced this issue in https://github.com/flexopticalHenno/issue-repro-electron-builder-local-dependency

**Comment by flexopticalHenno** [comment]
Thank you for the quick response and help. I believe that the third option will be working fine in my setup

**Comment by flexopticalHenno** [comment]
Interestingly enough, when I try to reproduce this in your demo with `files: ["**/*", "!test"]` it will pack the local dependency into `app.asar`. If I move the dependency into a subfolder `libs/test` and exclude `libs` instead, `test` will not be part of `node_modules` in `app.asar`

**Comment by beyondkmp** [comment]
> Interestingly enough, when I try to reproduce this in your demo with `files: ["**/*", "!test"]` it will pack the local dependency into `app.asar`. If I move the dependency into a subfolder `libs/test` and exclude `libs` instead, `test` will not be part of `node_modules` in `app.asar`

This should be a bug, which will be fixed in this https://github.com/electron-userland/electron-builder/pull/8406. Once fixed, you should not encounter any more issues if you directly place it in the libs directory.

**Comment by mmaietta** [comment]
@beyondkmp can you please take a look at this when you have another chance?

@wxfred do you happen to have a sample/minimum repro repo you could share here? Something we can quickly dive in deeper to debug your project setup?

**Comment by wxfred** [comment]
It's weird, i'm trying to create minimum project to reproduce this problem, if **app-server** only installs **koa**, the packed exe has nothing wrong.
But, after adding **@koa/router**, the error "Cannot find module 'koa-compose'" comes out.
Both **koa** and **@koa/router** depend on **koa-compose**, i don't know why adding **@koa/router** will cause this problem.

> [@wxfred](https://github.com/wxfred) do you happen to have a sample/minimum repro repo you could share here? Something we can quickly dive in deeper to debug your project setup?

@mmaietta There are my a little changes to @beyondkmp 's [hello.zip](https://github.com/user-attachments/files/16508485/hello.zip) to reproduce the problem below.

I create a folder **app** with [hello.zip](https://github.com/user-attachments/files/16508485/hello.zip) unzipped, and a folder **app-server** is created in the same dir as **app**.
There is only one file **server.js** in **app-server/src**, the codes are
```
const Koa = require('koa')
const Router = require('@koa/router') // If this line is annotated, the packed exe will not have any problems

exports.Server = () => {
  const app = new Koa()

  app.listen(3000, () => {
    console.log('app listen to 3000')
  })

  return app
}
``` 
make sure to run
> npm i koa @koa/router

under **app-server**

And then i make a little changes in **app**,
In **app/package.json**, I add **app-server** dependency, and @beyondkmp 's **copy-local-deps.js**
```
  ...
  "scripts": {
    ...
    "postinstall": "node copy-local-deps.js"
  },
  ...
  "dependencies": {
    ...
    "app-server": "file:../app-server"
  }
}
```

In **app/main.js**, i add a requirement of **app-server**
```
...
const { Server } = require('app-server/src/server.js')
const server = Server()
...
```

Everytime when you change **app-server**, remember to run **npm install** to invoke **copy-local-deps.js** under **app**.
You will reproduce my experience:
1. run **npm run start** under **app**, nothing wrong
2. run **npm run dist** and run the packed exe, error comes out
3. annotate **const Router = require('@koa/router')**, run **npm install** under **app** , then run **npm run dist** and run the packed exe, nothing wrong

**Comment by wxfred** [comment]
I add **"asar": false**, and find that
```
app
└dist
  └win-unpacked
     └resources
       └app
          └node_modules
            └app-server
              └node_modules
                └@koa
                |  └router
                |    └(no node_modules)
                └koa
                  └node_modules
                    └koa-compose (only this)
```
