### PR TITLE
fix: add support for pnpm 11

### LINKED ISSUE #9711: Packaged app dependencies are missing when using pnpm v11
**Electron-Builder Version:** 26.9.1
**Node Version:** 24.15.0
**Electron Version:** 41.1.1
**pnpm Version:** 11.0.8

After upgrading pnpm from v10.31.1 to v11.0.8, our packaged Electron app fails to start because a runtime dependency is not included in the packaged app:

```text
Uncaught Exception:
Error: Cannot find module '<abc>'
```
Our project uses pnpm workspaces, with the Electron app located in one workspace package.
From debugging, it looks like `electron-builder` collects production dependencies by running:
```
pnpm list --prod --json --depth Infinity --silent
```
The JSON output of this command appears to have changed between pnpm v10 and v11 for workspaces.

With pnpm v10, running the command from the workspace root and from a workspace package directory produced different results. A dependency declared only by a workspace package was listed only when the command was run from that package directory.

With pnpm v11, running the command from either the workspace root or the workspace package directory returns the same workspace-wide output, including all workspace packages and their dependencies.

I believe this can cause `electron-builder` to fail to collect app dependencies.

### PR DESCRIPTION
**Pull request by mmaietta**
- Fixes pnpm v11 workspace builds producing empty bundles (`Error: Cannot find module`) due to a breaking change in `pnpm list --json` output format
- pnpm v11 returns one array entry **per workspace package**; v10 returned the root entry with workspace packages nested as dependencies — electron-builder assumed the old layout and collected zero dependencies
- Detects pnpm major version via a `Lazy<number>` and exposes a version-aware `allWorkspacePackages` getter that returns the full multi-entry array for v11 and single-tree behavior for v10/non-workspace
- Adds a regression test using `pnpm@11.0.9` in a workspace fixture, including the required `allowBuilds: { electron: true }` in `pnpm-workspace.yaml` (pnpm v11 replaced `onlyBuiltDependencies` with this)

### CODE REVIEW

File: packages/app-builder-lib/src/node-module-collector/pnpmNodeModulesCollector.ts [hunk 1]
```diff
@@ -9,6 +10,29 @@ export class PnpmNodeModulesCollector extends NodeModulesCollector<PnpmDependenc
...
+  })
+
+  /**
+   * Returns the workspace packages to iterate over, gated by detected pnpm version:
+   * - pnpm v11+: multi-entry workspace output → return the full parsed array
+   * - pnpm < v11 / non-workspace / detection failure: single-tree behavior → return only [0]
+   */
+  private get allWorkspacePackages(): PnpmDependency[] {
+    if (this._pnpmMajorVersion >= 11) {
+      return this._allWorkspacePackages
```
Comment (beyondkmp) [inline packages/app-builder-lib/src/node-module-collector/pnpmNodeModulesCollector.ts:31]: We likely don't need to return all packages. It should be sufficient to just return the first workspace package and the app package whose names match. If this covers all use cases, we won't need to differentiate between PNPM v10 and v11 anymore.

Comment (mmaietta) [reply packages/app-builder-lib/src/node-module-collector/pnpmNodeModulesCollector.ts:31]: Thanks for the check! I don't think we can safely reduce to just the first + matching package though

pnpm v11 uses `dedupedDependenciesCount` to mark packages whose subtree has already been expanded *elsewhere in the same JSON output*. Our `collectDepsRecursively` skips any entry with `dedupedDependenciesCount > 0` (it can't recurse into a stub). `extractProductionDependencyGraph` then resolves those stubs by looking up the real entry in `allDependencies`.

As an example, if `app` and `lib` both depend on `lodash`, pnpm expands `lodash` fully only in whichever workspace package comes first in the array (which could be, `lib`) and marks it as deduped in the other package (`app`). If we only process the `app` entry, `lodash` is encountered as a deduped stub and skipped — it never enters `allDependencies`. When the production graph later tries to resolve it, it hits `PKG_DUPLICATE_REF_UNRESOLVED` and silently drops it. No error, just a missing module in the bundle.

We also can't fully eliminate the v10/v11 differentiation: `getTreeFromWorkspaces` still needs to know whether to look for the app nested in `[0].dependencies` (v10) or as a top-level entry (v11).
