### ISSUE TITLE
Broken types since v26

### ISSUE THREAD

**Issue by t3chguy** [electron-userland/electron-builder#8812]
Regressed by https://github.com/electron-userland/electron-builder/pull/8805

`node_modules/app-builder-lib/out/asar/integrity.d.ts(2,10): error TS2305: Module '"../fileMatcher"' has no exported member 'FileMatcher'.` https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/fileMatcher.ts#L41 prevents the type from being included in the resulting types

**Comment by t3chguy** [comment]
> Wait what, I'm not sure I follow. Is this a compile-time error with skipLibCheck: false? I'm trying to repro but can't seem to get the error.

Yes it is that, for consumers of `lib-app-builder` anyway - such as myself needing `computeData` to rebuild asar integrity after a universal pkg.

> Not sure why @internal is flagging anything.

`@internal` means the FileMatcher symbol is omitted from the output type, but `asar/integrity.ts` now imports and relies on that type in its method signature.

**Comment by t3chguy** [comment]
Looks great, will give it a test tomorrow. Thanks again

**Comment by mmaietta** [comment]
Deployed 26.0.1

**Comment by t3chguy** [comment]
Thanks @mmaietta can confirm that fixed it, and that the issues around asar integrity and electron fuses are both fixed in v26. Keep up the great work
