### ISSUE TITLE
Building NSIS installers broken after switching from 22.10.5 to 22.11.1

### ISSUE THREAD

**Issue by ezzatron** [electron-userland/electron-builder#5863]
* **Version**: 22.11.1

* **Electron Version**: 12.0.6
* **Electron Type (current, beta, nightly)**: current

* **Target**: Windows, NSIS, x64

After updating `electron-builder` from `22.10.5` to `22.11.1`, this error started happening for all of our Windows builds:

```
  • packager.vm is used: Cannot read property 'readFileSync' of undefined
(node:90934) UnhandledPromiseRejectionWarning: Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /path/to/project/node_modules/builder-util/src/util.ts:132:18
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:90934) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:90934) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After some digging, this seems to be an issue with how `app-builder-lib`'s TypeScript source is being compiled for distribution. The [original source](https://github.com/electron-userland/electron-builder/blob/master/packages/app-builder-lib/src/targets/nsis/nsisUtil.ts#L164) looks like this:

```ts
// ...

import fs from "fs"

// ...

export class UninstallerReader {
  // noinspection SpellCheckingInspection
  static exec(installerPath: string, uninstallerPath: string) {
    const buffer = fs.readFileSync(installerPath)

    // ...
  }
}
```

But in `22.11.1` this is being compiled to JavaScript that looks like this, where it expects the `fs` module to have a `.default` property, which it doesn't (basically assuming it's an ES module):

```js
// ...

const fs_2 = require("fs");

// ...

class UninstallerReader {
    // noinspection SpellCheckingInspection
    static exec(installerPath, uninstallerPath) {
        const buffer = fs_2.default.readFileSync(installerPath); // <-- fs_2.default is undefined here

        // ...
    }
}
```

Looking at the distributed Javascript for the previous version (`22.10.5`), it seems like this case is handled by the compiled output:

```js
// ...

var _fs2 = _interopRequireDefault(require("fs"));

// ...

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// ...

class UninstallerReader {
  // noinspection SpellCheckingInspection
  static exec(installerPath, uninstallerPath) {
    const buffer = _fs2.default.readFileSync(installerPath);

    // ...
  }

}
```

The `_interopRequireDefault` function seems to be something that used to be added by [@babel/plugin-transform-modules-commonjs](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs). My current theory is that something broke the Babel integration between these two versions.

**Comment by 20vitality12** [comment]
Thank you! It`s help me to make buld for win. 22.10.5 work fine

**Comment by omarkilani** [comment]
@mmaietta 22.11.2 is still broken, and this is on macOS (we use 22.10.4 right now as 22.10.5 has some issue building native modules):

```
% git diff
diff --git a/package.json b/package.json
index 5e93206..2045da7 100644
--- a/package.json
+++ b/package.json
@@ -23,7 +23,7 @@
   "devDependencies": {
     "async": "^3.2.0",
     "electron": "^12.0.6",
-    "electron-builder": "22.10.4",
+    "electron-builder": "^22.11.2",
     "electron-builder-squirrel-windows": "^22.11.1",
     "electron-notarize": "^1.0.0",
     "electron-rebuild": "^2.3.5",
```

```
% yarn
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ electron-builder install-app-deps
  • electron-builder  version=22.10.5
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=darwin arch=arm64 appDir=/blah/app
✨  Done in 1.44s.
```

Note how the version says 22.10.5 for some reason, even though we were on 22.10.4.

**Comment by ezzatron** [comment]
Not working for me either. I get the same error. Perhaps it's to do with the [`esModuleInterop` setting](https://www.typescriptlang.org/tsconfig#esModuleInterop)? I noticed that setting is [explicitly set to `false`](https://github.com/electron-userland/electron-builder/blob/ea315aa11528a44189c860d22ce04e59b9ed6c64/tsconfig-base.json#L5) in electron-builder's config.

**Comment by omarkilani** [comment]
This is, for whatever reason, still broken for us on 22.11.3, @develar .

```
% rm -rf node_modules 
% rm -rf app/node_modules 
% rm yarn.lock 
% rm app/yarn.lock
 
% yarn
yarn install v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning electron-rebuild > lzma-native > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning electron-rebuild > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning electron-rebuild > node-gyp > request > har-validator@5.1.5: this library is no longer supported
[2/4] 🚚  Fetching packages...
info google-closure-compiler-windows@20210505.0.0: The platform "darwin" is incompatible with this module.
info "google-closure-compiler-windows@20210505.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info google-closure-compiler-windows@20210505.0.0: The CPU architecture "arm64" is incompatible with this module.
info google-closure-compiler-linux@20210505.0.0: The platform "darwin" is incompatible with this module.
info "google-closure-compiler-linux@20210505.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info google-closure-compiler-linux@20210505.0.0: The CPU architecture "arm64" is incompatible with this module.
info google-closure-compiler-osx@20210505.0.0: The CPU architecture "arm64" is incompatible with this module.
info "google-closure-compiler-osx@20210505.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder  version=22.10.5
  • loaded configuration  file=package.json ("build" field)
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • installing production dependencies  platform=darwin arch=arm64 appDir=/blah/app
✨  Done in 29.81s.

% fgrep version node_modules/electron-builder/package.json 
	"version": "22.11.3",

% node -v 
v16.1.0

% yarn -v
1.22.10

% npm -v
7.11.2
```

**Comment by mmaietta** [comment]
@omarkilani , electron-builder 22.11.x currently does not work on node 16, not sure if it did previously in 22.10. 
Ref: https://github.com/electron-userland/electron-builder/issues/5858 https://github.com/electron-userland/electron-builder/issues/5874

**Comment by omarkilani** [comment]
@mmaietta ah, okay. Yeah it works great on 22.10.4.

https://github.com/electron-userland/electron-builder/issues/5668#issuecomment-826941928

Forgot about that, though it looks like @develar made some other changes there that might help.

**Comment by omarkilani** [comment]
FWIW, 22.11.4 works, and appears to work on node 16. Thanks @develar !

**Comment by Stanzilla** [comment]
install-app-deps fails for me on 22.11.4

```
> electron-builder install-app-deps

Error: Cannot find module 'fs/promises'
Require stack:
- /home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/builder-util/out/fs.js
- /home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/builder-util/out/util.js
- /home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/electron-builder/out/cli/cli.js
- /home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/WeakAuras-Companion/WeakAuras-Companion/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```

https://github.com/WeakAuras/WeakAuras-Companion/pull/1044/checks?check_run_id=2586016028

**Comment by angelnavarro** [comment]
Working with electron-builder 22.11.7 and node 14.17.3.

**Comment by sandeep1995** [comment]
Doesn't work on Nodejs 12.21.0 32 bit on macOS. 
```
Error: Cannot find module 'fs/promises' 
```

**Comment by mmaietta** [comment]
@sandeep1995 that's because newer versions of electron-builder requires node 14+
