### ISSUE TITLE
Cannot find type definition file for 'node/http' after update to 22.5.1

### ISSUE THREAD

**Issue by sapkra** [electron-userland/electron-builder#4887]
* **Version**: 22.5.1 (22.4.1 is working fine)
* **Electron Version**: 8.2.3
* **Electron Type (current, beta, nightly)**: current
* **Target**: win, linux, mac

```bash
../../node_modules/app-builder-lib/out/publish/PublishManager.d.ts:1:23 - error TS2688: Cannot find type definition file for 'node/http'.

1 /// <reference types="node/http" />
                        ~~~~~~~~~
```

I'm getting this error while building hooks using using webpack. I'm using the following import:
```typescript
import { AfterPackContext } from 'electron-builder';
```

#### PublishManager.d.ts of 22.4.1
```typescript
/// <reference types="node" />
...
```

#### PublishManager.d.ts of 22.5.1
```typescript
/// <reference types="node/http" />
...
```

Edit: 22.7.0 is still broken

**Comment by sapkra** [comment]
I found the following on stackoverflow. Maybe it is helpful for fixing the bug.
https://stackoverflow.com/questions/59293719/typescript-generates-invalid-triple-slash-directive/59439226

**Comment by Armaldio** [comment]
Can confirm, same error

**Comment by sapkra** [comment]
@develar Can you have a look at this problem please. The library is unusable with this problem.

**Comment by Armaldio** [comment]
One solution is to use skipLibCheck
Please, check this issue

**Comment by RogerBaracy** [comment]
adiciona o // @ts-ignore na linha 1 do arquivo:
../../node_modules/app-builder-lib/out/publish/PublishManager.d.ts 

Pelo o que eu entendi  "node/http" sofreu alguma alteração entre as versão 10 e 14 do Node,
o mais correto seria atualizar as definições de tipo nesse arquivo.

**Comment by sapkra** [comment]
I've setup a new project with the latest electron and electron-builder and have no problems anymore. I don't know why, but that's the case somehow.
