### ISSUE TITLE
Windows build broken after switching from 22.10.5 to 22.11.3 

### ISSUE THREAD

**Issue by LeonanCarvalho** [electron-userland/electron-builder#5879]
* **Version**:  22.11.3
* **Electron Version**: v12.0.7

* **Target**:  nsis , msi 32 and 64bits

The first notable thing is even that electron-builder --version output: 22.11.3  when the build process starts it displays  version=22.10.5

It was working on 22.10.5 but doesn't at the latest version.

```

 electron-builder --win --ia32 --x64 --publish always

  • electron-builder  version=22.10.5 os=10.0.19043
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  file=D:\DEV\electron\master-updater\node_modules\electron-webpack\out\electron-builder.js
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=12.0.7 appOutDir=dist\win-unpacked
  • server doesn't support ranges

```
the file called `__uninstaller-nsis-app.exe`  is missing

```
SignTool Error: File not found: D:\DEV\electron\dist\__uninstaller-nsis-app.exe

    at D:\DEV\electron\node_modules\builder-util\src\util.ts:132:18
    at ChildProcess.exithandler (child_process.js:326:5)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
```

And after upload assets to github:

```

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Innadril@1.1.4 release: `electron-builder --win --ia32 --x64 --publish always`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Innadril@1.1.4 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-05-12T01_38_04_673Z-debug.log

```

debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'release'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info lifecycle App@1.1.4~prerelease: App@1.1.4
6 info lifecycle App@1.1.4~release: App@1.1.4
7 verbose lifecycle App@1.1.4~release: unsafe-perm in lifecycle true
8 verbose lifecycle App@1.1.4~release: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\DEV\electron\node_modules\.bin;D:\DEV\electron\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Google\Chrome\Application;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;%PATH%;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\DDS Utilities;C:\Program Files\java\jdk-14.0.1\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PhpStorm 2020.1.1\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1.1\bin;C:\ProgramData\npm;C:\Users\user\AppData\Roaming\npm;C:\Program Files\Git\bin;D:\PHP7;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PowerShell\7-preview\preview;C:\Program Files (x86)\NVIDIA Corporation\DDS Utilities;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Subversion\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\IncrediBuild;D:\DEV\desktop\vcpkg;C:\Program Files\CMake\bin;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\java\jdk-14.0.1\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PhpStorm 2020.2.3\bin;;D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3\bin;;C:\ProgramData\npm;C:\Users\user\AppData\Roaming\npm;C:\Program Files\Git\bin;D:\PHP7;D:\Program Files (x86)\Nmap;D:\DEV\desktop\vcpkg;C:\Users\user\AppData\Local\Yarn\bin;C:\Program Files\java\jdk-14.0.1\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PhpStorm 2020.2.3\bin;;D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3\bin;;C:\ProgramData\npm;C:\Program Files\Git\bin;D:\PHP7;D:\Program Files (x86)\Nmap;D:\DEV\desktop\vcpkg;C:\Users\user\AppData\Local\Yarn\bin;C:\Users\user\AppData\Roaming\npm
9 verbose lifecycle App@1.1.4~release: CWD: D:\DEV\electron
10 silly lifecycle App@1.1.4~release: Args: [ '/d /s /c', 'electron-builder --win --ia32 --x64 --publish always' ]
11 silly lifecycle App@1.1.4~release: Returned: code: 1  signal: null
12 info lifecycle App@1.1.4~release: Failed to exec release script
13 verbose stack Error: App@1.1.4 release: `electron-builder --win --ia32 --x64 --publish always`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid App@1.1.4
15 verbose cwd D:\DEV\electron
16 verbose Windows_NT 10.0.19043
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error App@1.1.4 release: `electron-builder --win --ia32 --x64 --publish always`
22 error Exit status 1
23 error Failed at the App@1.1.4 release script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by mmaietta** [comment]
>  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
Hi @develar, we might have another compilation issue on 22.11.3. Could you please assist again?
```
const update_notifier_1 = require("update-notifier");
...
const notifier = update_notifier_1.default({ pkg: it });
```

**Comment by nathanlesage** [comment]
I can confirm that Electron builder also has stopped building other operating system's assets as well in 22.11.3. After installing I get this output:

```
[4/4] 🔨  Building fresh packages...
$ electron-builder install-app-deps
  • electron-builder  version=22.10.5
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • loaded configuration  file=/Users/hendrik/Documents/dev/Zettlr/electron-builder.yml
✨  Done in 28.14s.
```

And when trying to build something (in my case it was a macOS ARM DMG build):

```
$ electron-builder --mac --arm64 --publish never --prepackaged out/Zettlr-darwin-arm64/Zettlr.app
  • electron-builder  version=22.10.5 os=20.4.0
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • loaded configuration  file=/Users/hendrik/Documents/dev/Zettlr/electron-builder.yml
  • writing effective config  file=release/builder-effective-config.yaml
  ⨯ dlopen(/Users/hendrik/Documents/dev/Zettlr/node_modules/iconv-corefoundation/lib/native.node, 1): no suitable image found.  Did find:
        /Users/hendrik/Documents/dev/Zettlr/node_modules/iconv-corefoundation/lib/native.node: mach-o, but wrong architecture
        /Users/hendrik/Documents/dev/Zettlr/node_modules/iconv-corefoundation/lib/native.node: mach-o, but wrong architecture  failedTask=build stackTrace=Error: dlopen(/Users/hendrik/Documents/dev/Zettlr/node_modules/iconv-corefoundation/lib/native.node, 1): no suitable image found.  Did find:
        /Users/hendrik/Documents/dev/Zettlr/node_modules/iconv-corefoundation/lib/native.node: mach-o, but wrong architecture
        /Users/hendrik/Documents/dev/Zettlr/node_modules/iconv-corefoundation/lib/native.node: mach-o, but wrong architecture
```

Additionally, I can confirm 22.10.5 worked fine.

***

Platform: macOS 11.3 (ARM arch)

**Comment by Lyrei-cm** [comment]
This issue is preventing me from releasing my app. 😔 Could this be addressed within the next 24 hours, please? 🙏

**Comment by nathanlesage** [comment]
@Lyrei-cm You can release your app with 22.10.5, which works fine. 24h response within the area of Open Source is a bit demanding.

**Comment by LeonanCarvalho** [comment]
I consider this bug critical because it was released at the stable npm channel.

I have no idea what broken the code.

**Comment by Lyrei-cm** [comment]
> @Lyrei-cm You can release your app with 22.10.5, which works fine. 24h response within the area of Open Source is a bit demanding.

I cannot due to the 50MB file size limit.

I didn't mean to come across as demanding. Just desperate. 😭

**Comment by nathanlesage** [comment]
@Lyrei-cm What size limit? Electron-builder shouldn't impose a file size of any kind. What are you referring to?

**Comment by LeonanCarvalho** [comment]
The issue also confirmed in any 22.11.x version, it's not stable, everyone should roll back to 22.10.5

**Comment by LeonanCarvalho** [comment]
I made a test with Node 16 instead 14(lts) and the error output is different(but same), something related to nsis __unistaller


```
Number of errors: 1

SignTool Error: The file is being used by another process.
SignTool Error: An error occurred while attempting to sign: project\dist\__uninstaller-nsis-app.exe

    at project\node_modules\builder-util\src\util.ts:132:18
    at ChildProcess.exithandler (node:child_process:333:5)
    at ChildProcess.emit (node:events:365:28)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by develar** [comment]
Please try 22.11.4.

**Comment by nathanlesage** [comment]
@develar Just tried that out, and I can confirm 22.11.4 works as expected (on macOS 11.3 ARM arch), so the bug seems to have happened somewhere between 4 and 5

**Comment by LeonanCarvalho** [comment]
Ita a premature close.
I removed msi target and artifacts custom name from config and the build worked.

But now the application is facing some  "Error: EPERM: operation not permitted, open" and closing.

Something related to: config 

"requestedExecutionLevel": "requireAdministrator"

**Comment by bromix** [comment]
I still see the message under windows.

```
> electron-builder install-app-deps

  • electron-builder  version=22.10.5
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
```

I'm using version `22.11.1`

**Comment by mmaietta** [comment]
Please use a newer version @bromix. The CLI version fix was merged only 5 days ago: https://github.com/electron-userland/electron-builder/pull/5882

@LeonanCarvalho  can you please comment here with more logs using env var `DEBUG='electron-builder'`? You mentioned removing a custom artifact name. Curious if your issue is related to the introduction of this feature: https://github.com/electron-userland/electron-builder/pull/5718

**Comment by leopucci** [comment]
problem stills happens on `electron-builder  version=22.11.7 os=10.0.19043` windows 10
`File not found: __uninstaller-nsis-app.exe`

Rolling back to ` 22.10.5` builds ok as described above
