### ISSUE TITLE
Latest version does not work on MacOS 10.11

### ISSUE THREAD

**Issue by hrueger** [electron-userland/electron-builder#5974]
* **Version**: 22.11.7

* **Electron Version**: 13.1.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: MacOS x86

I have a Mac running OSX 10.11 . When using an older version of `electron-builder` like 22.10.5 everything works fine. With the latest version, however, I get the following error:
```
  • electron-builder  version=22.11.7 os=15.6.0
  • loaded configuration  file=/Users/Hannes/_Source/Glue/Glue/electron-builder.json
  • writing effective config  file=/Users/Hannes/_Source/Glue/release/builder-effective-config.yaml
dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/Hannes/_Source/Glue/Glue/node_modules/app-builder-bin/mac/app-builder
  Expected in: flat namespace

  ⨯ /Users/Hannes/_Source/Glue/Glue/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  failedTask=build stackTrace=Error: /Users/Hannes/_Source/Glue/Glue/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
    at ChildProcess.<anonymous> (/Users/Hannes/_Source/Glue/Glue/node_modules/builder-util/src/util.ts:249:14)
    at Object.onceWrapper (events.js:482:26)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

Is MacOS 10.11 not supported anymore in the latest release?

**Comment by mmaietta** [comment]
Hmmm, nothing should have changed that would impact it AFAIK in terms of supporting 10.11.
What version of node are you using?

**Comment by hrueger** [comment]
I'm using Node `14.17.1`.

**Comment by hrueger** [comment]
It's definitely not related to Electron, I tried Electron 11, 12 and 13. They all work with `electron-builder` `22.10.5`, but not with `22.11.7`.

**Comment by mmaietta** [comment]
@develar any thoughts on what could drop macos 10.11 support?

@hrueger would you be willing to try node 16 and also any earlier 22.11.x versions of electron builder, such as 22.11.3? Trying to collect test data.

Not sure if I can set up a MacOS 10.11 computer at this time.

**Comment by hrueger** [comment]
@mmaietta Sure, I just tried all `22.11.x` versions. As you can see, they all don't work.

<table>
<thead>
<tr>
	<th>Version</th>
	<th>Working on OSX 10.11?</th>
</tr>
</thead>
<tr>
	<td><code>22.11.7</code></td>
	<td>No ❌</td>
</tr>
<tr>
	<td><code>22.11.6</code></td>
	<td>No ❌</td>
<tr>
<tr>
	<td><code>22.11.5</code></td>
	<td>No ❌</td>
<tr>
<tr>
	<td><code>22.11.4</code></td>
	<td>No ❌</td>
<tr>
<tr>
	<td><code>22.11.3</code></td>
	<td>No ❌</td>
<tr>
<tr>
	<td><code>22.11.2</code></td>
	<td>No ❌</td>
<tr>
<tr>
	<td><code>22.11.1</code></td>
	<td>No ❌</td>
<tr>
<tr>
	<td><code>22.10.5</code></td>
	<td>Yes ✔</td>
<tr>
</table>

I read on the web that the error comes from changing the minimum OSX SDK version (https://github.com/pocoproject/poco/issues/1453) but I'm not familiar with OSX and its SDKs.

**Comment by mmaietta** [comment]
Many thanks for checking. This could be related as it's the only mac-specific code I found changing between those two versions
https://github.com/electron-userland/electron-builder/commit/469b85fa2a2660eaba1eafbbd528abec2b1f50d9

Would you be willing to give this patch a try? You can apply it locally to your project with [`patch-package`](https://www.npmjs.com/package/patch-package)

`dmg-builder+22.11.7.patch`
```
diff --git a/node_modules/dmg-builder/out/dmg.js b/node_modules/dmg-builder/out/dmg.js
index 7597fa2..a7b4765 100644
--- a/node_modules/dmg-builder/out/dmg.js
+++ b/node_modules/dmg-builder/out/dmg.js
@@ -173,14 +173,15 @@ async function createStageDmg(tempDmg, appPath, volumeName) {
     if (builder_util_1.log.isDebugEnabled) {
         imageArgs.push("-debug");
     }
-    let filesystem = ["HFS+", "-fsargs", "-c c=64,a=16,e=16"];
-    if (process.arch === "arm64") {
+    if (process.arch !== "arm64") {
+        imageArgs.push("-fs", "HFS+", "-fsargs", "-c c=64,a=16,e=16");
+    }
+    else {
         // Apple Silicon `hdiutil` dropped support for HFS+, so we force the latest type
         // https://github.com/electron-userland/electron-builder/issues/4606
-        filesystem = ["APFS"];
         builder_util_1.log.warn(null, "Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+");
+        imageArgs.push("-fs", "APFS");
     }
-    imageArgs.push("-fs", ...filesystem);
     imageArgs.push(tempDmg);
     // The reason for retrying up to ten times is that hdiutil create in some cases fail to unmount due to "resource busy".
     // https://github.com/electron-userland/electron-builder/issues/5431

```

**Comment by hrueger** [comment]
Sure, I'll do that tomorrow.

**Comment by hrueger** [comment]
@mmaietta Nope, unfortunately, it didn't change anything. 

I actually don't think that we can fix this by changing JS code, as the error comes from `/Users/Hannes/_Source/Glue/Glue/node_modules/app-builder-bin/mac/app-builder` which is an executable. Maybe the version of this package has changed and now that executable has been compiled with different settings?

**Comment by hrueger** [comment]
Yes, still an issue :-)

**Comment by mmaietta** [comment]
Taking a quick look between 22.10.5 and 22.11.0 is showing a jump in the node version 8->12. But you said you're using 14, so I still don't understand what would have impacted you. The compilation was migrated from `babel` to `tsc`

**Comment by hrueger** [comment]
Yes, I was using Node 14. Strange...

**Comment by Hardik500** [comment]
this is still relevant

**Comment by kburns2kb** [comment]
Hi, just had this issue myself

**Comment by ramiel** [comment]
Any news on this?
