### ISSUE TITLE
Packaged app dependencies are missing when using pnpm v11

### ISSUE THREAD

**Issue by gzdunek** [electron-userland/electron-builder#9711]
**Electron-Builder Version:** 26.9.1
**Node Version:** 24.15.0
**Electron Version:** 41.1.1
**pnpm Version:** 11.0.8

After upgrading pnpm from v10.31.1 to v11.0.8, our packaged Electron app fails to start because a runtime dependency is not included in the packaged app:

```text
Uncaught Exception:
Error: Cannot find module '<abc>'
```
Our project uses pnpm workspaces, with the Electron app located in one workspace package.
From debugging, it looks like `electron-builder` collects production dependencies by running:
```
pnpm list --prod --json --depth Infinity --silent
```
The JSON output of this command appears to have changed between pnpm v10 and v11 for workspaces.

With pnpm v10, running the command from the workspace root and from a workspace package directory produced different results. A dependency declared only by a workspace package was listed only when the command was run from that package directory.

With pnpm v11, running the command from either the workspace root or the workspace package directory returns the same workspace-wide output, including all workspace packages and their dependencies.

I believe this can cause `electron-builder` to fail to collect app dependencies.

**Comment by mmaietta** [comment]
Oh what the hell. pnpm changed their API again?? At least they didn't do it within the same v10 semver without a major bump - like previously... but still, this is frustrating.

I'll take a look at this soon. Need to wrap up a plethora of other workflows.
