### ISSUE TITLE
v22.11.1 intrododuces publishing bug

### ISSUE THREAD

**Issue by mixmix** [electron-userland/electron-builder#5861]
## Problem

**Node:** 14.16.1
**OS**: Linux, MacOS
 
have noticed the following error with publishing builds with `v22.11.1` :

```bash
> electron-builder --config build/electron-builder.config.js --publish always

  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • electron-builder  version=22.10.5 os=5.4.0-72-generic
  • loaded configuration  file=/home/somename/projects/AHAU/whakapapa-ora/desktop/build/electron-builder.config.js
  • writing effective config  file=dist/installers/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=fd-lock@1.2.0, fsctl@1.0.0, leveldown@5.6.0, sodium-native@3.2.1, utp-native@2.4.0 platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=12.0.6 appOutDir=dist/installers/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/installers/ahau-desktop-Linux-1.3.1-x86_64.AppImage
  • publishing      publisher=Github (owner: protozoa-nz, project: whakapapa-ora, version: 1.3.1)
  • uploading       file=ahau-desktop-Linux-1.3.1-x86_64.AppImage provider=GitHub
  ⨯ Cannot read property 'getType' of undefined  failedTask=build stackTrace=TypeError: Cannot read property 'getType' of undefined
    at GitHubPublisher.doUploadFile (/home/somename/projects/AHAU/whakapapa-ora/desktop/node_modules/electron-publish/src/gitHubPublisher.ts:190:36)
    at GitHubPublisher.doUpload (/home/somename/projects/AHAU/whakapapa-ora/desktop/node_modules/electron-publish/src/gitHubPublisher.ts:170:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at GitHubPublisher.upload (/home/somename/projects/AHAU/whakapapa-ora/desktop/node_modules/electron-publish/src/publisher.ts:87:5)
    at async Promise.all (index 1)
    at AsyncTaskManager.awaitTasks (/home/somename/projects/AHAU/whakapapa-ora/desktop/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at PublishManager.awaitTasks (/home/somename/projects/AHAU/whakapapa-ora/desktop/node_modules/app-builder-lib/src/publish/PublishManager.ts:228:5)
    at Object.executeFinally (/home/somename/projects/AHAU/whakapapa-ora/desktop/node_modules/builder-util/src/promise.ts:23:3)
```

## Investigation

Looked at `/home/somename/projects/AHAU/whakapapa-ora/desktop/node_modules/electron-publish/src/gitHubPublisher.ts:190:36` and it's saying `mime` is undefined which is pretty strange

```bash
➜  desktop git:(master) npm ls mime --depth 5
ahau-desktop@1.3.1 /home/somename/projects/AHAU/whakapapa-ora/desktop
├─┬ electron-builder@22.11.1
│ └─┬ app-builder-lib@22.11.1
│   └─┬ electron-publish@22.11.1
│     └── mime@2.5.2 deduped

```

hmmm

## Fix

regress to `v22.10.5`

**Comment by cawa-93** [comment]
I can confirm: https://github.com/cawa-93/vite-electron-builder/runs/2507942045

**Comment by modmoto** [comment]
@mixmix 
What tool did you downgrade? We tried `electron-publish` but that did not work

**Comment by mixmix** [comment]
Electron-builder

**Comment by cawa-93** [comment]
Ping @develar @mmaietta

**Comment by mixmix** [comment]
BTW, I'm totally happy using the earlier version. I'm incredibly grateful
for the work that's been put into this module.

It's making building traditional knowledge management software for Māori
communities in New Zealand.

Opened this issue just for visibility

**Comment by mmaietta** [comment]
There were a lot of changes between 22.10.5 to 22.11.1, which makes this so much more difficult to triage.
Few changes that I've collected so far that I think could create this.
`ts-babel` -> `tsc`
`yarn` -> `pnpm`
```
    "target": "es2018", -> es2019
    "module": "esnext", -> CommonJS
```
I have no idea how to test to fix this though as I don't have any publisher setups to work with.

Could someone please put together a minimal-reproducing repo/gist?

**Comment by cawa-93** [comment]
> There were a lot of changes between 22.10.5 to 22.11.1, which makes this so much more difficult to triage.
> Few changes that I've collected so far that could potentially relate to this.
> `ts-babel` -> `tsc`
> `yarn` -> `pnpm`
> ```
>     "target": "es2018", -> es2019
>     "module": "esnext", -> CommonJS
> ```
> I have no idea how to test to fix this though as I don't have any publisher setups to work with.
> 
> Could someone please put together a minimal-reproducing repo/gist?

You can use my template repo, if this help ...
https://github.com/cawa-93/vite-electron-builder/

**Comment by bcomnes** [comment]
> Could someone please put together a minimal-reproducing repo/gist?

I wrote up the problem in the published package:

https://github.com/electron-userland/electron-builder/pull/5870#issuecomment-836743687

Basically, the tests are treating `module.exports` in `mime` as a default import, but is treating `module.exports` as an object of named exports and looking for a `default` property on that object in the published asset.  Since `mime` doesn't export an object with a `default` property,  you will see these `.default is not a function` errors wherever a cjs module is imported.

**Comment by develar** [comment]
Fix: `import * as mime from "mime"` instead of `import mime from "mime"`. Will be pushed soon.
