### ISSUE TITLE
AppImage (linux) target fails with node 16

### ISSUE THREAD

**Issue by ashpieboop** [electron-userland/electron-builder#5874]
* **Version**: 22.11.3

* **Electron Version**: 12.0.7
* **Electron Type (current, beta, nightly)**: current

* **Target**: AppImage (linux)

npm version 7.12.0
yarn version 1.22.10
I'm building on linux (up-to-date archlinux install).

Logs with node 16.1.0 (fails):
```
ashpie@darla ~/d/tabs (develop)> electron-builder -l
  • electron-builder  version=22.10.5 os=5.12.2-zen1-1-zen
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=12.0.7 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/tabs-1.2.11.AppImage
(node:47257) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
  ⨯ ENOENT: no such file or directory, stat '/home/ashpie/dev/tabs/dist/__appImage-x64'  failedTask=build stackTrace=Error: ENOENT: no such file or directory, stat '/home/ashpie/dev/tabs/dist/__appImage-x64'
  ```

Logs with node 15.14.0 (success):
```
ashpie@darla ~/d/tabs (develop)> electron-builder -l
  • electron-builder  version=22.10.5 os=5.12.2-zen1-1-zen
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=12.0.7 appOutDir=dist/linux-unpacked
  • building        target=AppImage arch=x64 file=dist/tabs-1.2.11.AppImage
```
Also, the reported version in logs is `22.10.5`, but `electron-builder --version` reports `22.11.3`.

package.json: https://eternae.ink/ashpie/tabs/src/branch/node-16/package.json
(all dependencies are up-to-date)

**Comment by mmaietta** [comment]
Related: #5858

**Comment by marckohlbrugge** [comment]
I'm running into this same bug on nodejs 16. I'm able to work around it by manually creating the `__appImage-x64` directory first. That way when it tries to delete it, it actually succeeds.

**Comment by ashpieboop** [comment]
I upgraded to node 16.2.0

- electron-builder 22.11.3 still fails with exact same logs
- electron-builder 22.11.4 seems to have fixed the issue, 22.11.5 works fine too
- upgrading everything to latest version including electron 13.x still works fine with 22.11.5

I believe this issue is fixed, feel free to open again if there is more to it.
