### PR TITLE
fix: allow custom electron zip name to be provided when unpacking a provided electronDist

### PR DESCRIPTION
**Pull request by mmaietta**

### CODE REVIEW

**Comment by panther7** [comment]
This PR is broken, if `electronDist` is unpacked Electron. Works in 26.0.15 and below.

@mmaietta

**Comment by mmaietta** [comment]
Checking asap

**Comment by mmaietta** [comment]
I can't seem to reproduce your issue. Just wrote a full unit test for an unpacked electron directory and it still passes correctly AFAICT.

Can you share your electron-builder config for `electronDist`?

**Comment by panther7** [comment]
Is there any way I can test a specific commit?

```
yarn add electron-builder@github:electron-userland/electron-builder#2d014a86050eee16e4092cfce40a1a6e9c9ee474
```

yarn 3+ is "broken" to checkout from github.

**Comment by panther7** [comment]
1. Conf in `26.0.15`: `electronDist: 'node_modules/electron/dist'` - works
1. Conf in `26.0.16`: `electronDist: 'node_modules/electron/dist'` - error
    ```
    Error: Failed to resolve electronDist: Cannot find module '###\node_modules\electron\dist'
    ```
1. Conf in `26.0.16`: `electronDist: 'node_modules/electron'` - error
    ```
    [Error: ENOENT: no such file or directory, rename '###\win-unpacked\electron.exe' -> '###\win-unpacked\MyApp.exe'] {
      errno: -4058,
      code: 'ENOENT',
      syscall: 'rename',
      path: '###\\win-unpacked\\electron.exe',
      dest: '###\\win-unpacked\\MyApp.exe'
    }
    ```

**Comment by mmaietta** [comment]
Is your electron a custom already-branded executable? E.g. the electronDist doesn't have `electron.exe`?

Apologies on the back and forth here. I'm also reachable via the Electron discord if that's easier to collaborate through

**Comment by panther7** [comment]
Works again in `26.0.17`, good job.
