### ISSUE TITLE
Cannot find module with version 25

### ISSUE THREAD

**Issue by lannodev** [electron-userland/electron-builder#8784]
Hello!
After upgrading **electron-builder** from **24.13.3** to **25.1.8** I'm having problems building my application.

I recived this error message when building using version **25**:

![Image](https://github.com/user-attachments/assets/68f6ff78-d62f-486e-9eba-63a58aae462e)

I'm using `@tensorflow/tfjs-node` package, and when I investigated the problem I noticed that `app.asar` file is missing some folders.
I extracted app.asar using the command ` npx @electron/asar extract app.asar <destfolder>` 

Version 25:

![Image](https://github.com/user-attachments/assets/70eef3e0-ee07-4628-ad8f-d6120f92404c)

Version 24:

![Image](https://github.com/user-attachments/assets/32d54ec9-01d6-436d-8430-0e053ca51602)

Please, is this a bug or something that changed in this latest version?

All the best!

**Comment by mmaietta** [comment]
Can you please try `next` tag for electron-builder? It was migrated to the official electron/asar package and the packaging logic was upgraded

**Comment by lannodev** [comment]
@mmaietta Thank you, It's working on version **26.0.0-alpha.9**
Is there any date for the stable version?

**Comment by mmaietta** [comment]
Very soon ^_^

Can't provide a specific date atm as I just released `alpha.9` and new docker images were just deployed upgrading from `focal` to `jammy` (22.04) w/ new node22 images provided in order to support latest `wine`. So I was hoping to let that sit for a week or so in case any user issues are reported before exiting `alpha`.
