### ISSUE TITLE
Don't publish by default on github builds

### ISSUE THREAD

**Issue by pimterry** [electron-userland/electron-builder#5463]
* **Version**: 22.9.1

When setting up a new github actions build, it attempts to publish the result automatically to github by default. I only noticed this because I received an unexpected error at the end of my build:

```
  ⨯ GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
```

This was a normal branch build, not tagged or anything, which I'd never normally want to publish.

This behaviour is pretty surprising, and in many cases it's a serious security risk if you don't expect it when there's github token in the environment for some other reason. Build output even in open source repos could easily contain secrets, especially when you're first setting up a new build - it would be easy for this to accidentally publish your code signing keys, for example.

Also, this surprising behaviour isn't documented - there's no default value for publish listed on the [config value](https://www.electron.build/configuration/publish) or [CLI arguments](https://www.electron.build/cli).

There's been quite a few issues discussing this in the past, all now closed due to inactivity, e.g. https://github.com/electron-userland/electron-builder/issues/4546 and https://github.com/electron-userland/electron-builder/issues/1693. I think it's pretty clear that this is causing confusion.

**Are you be open to disabling this?** I think it's just a matter of making `null` the default value for publish config (that's the current workaround for this behaviour). I'd be happy to put a PR together for this, if you're open to that.

In general, I'd personally prefer to have `electron-builder publish` as a separate action, so I can build that into my CI workflow in more complex ways (e.g. testing a built distributable before it's published) but that's a separate question, and being able to opt-in with `--publish` is fine for now.

**Comment by pimterry** [comment]
This is still relevant, and AFAIK there's nothing blocking it and it's very easy to do (although it is a breaking change!). It would be great to hear thoughts from the maintainers on this issue.

**Comment by adityaruplaha** [comment]
Still an issue, I don't know why this behaviour was selected as default.

**Comment by Apak00** [comment]
Seems like it tries to publish when my package.json script is named "release" and it does not when the name is something else like "dist".

**Comment by vraravam** [comment]
This was working correctly in version `22.11.3`, but has regressed in `22.11.7`. Can it be fixed please? We are unable to build for non-release builds where we do NOT want to publish the built artifacts.

**Comment by pimterry** [comment]
This is still relevant, it has a fair few votes now, and AFAIK there's nothing blocking it and it's very easy to do (although it is a breaking change!). It would be great to hear thoughts from the maintainers on this issue.

**Comment by ferdodo** [comment]
I was also surprised by this behavior.

**Comment by hovancik** [comment]
`node_modules/.bin/electron-builder --linux snap -c.snap.publish=never` is not working for me :( 

```
⨯ Cannot find module 'electron-publisher-never'
```

**Comment by JackDotJS** [comment]
honestly shocked to see that this is nearly 4 years old and counting. i started a project that uses electron-builder recently, and have only now gotten around to setting up a workflow to automatically make snapshot builds of my app. what i was not expecting at all was the build to immediately fail because it didn't have a github token.... *huh???* why the hell does it need that???????

oh, because it wants to create a release build.... so glad that there was plenty of forewarning and documentation on this feature and that i didn't have to search far and wide for an entire hour until i uncovered this nearly 4 year old github issue. 😬

**Comment by mmaietta** [comment]
I'd be open to having it deactivated by default for a v26.

This is the logic determining whether publishing is performed. There are some aspects of it that assume auto-detection based on if a git Tag exists or `npm_lifecycle_event === "release"`. It already logs for most of the "auto" cases, except for `npm_lifecycle_event` which I'm not familiar with.

https://github.com/electron-userland/electron-builder/blob/afd813265d346b7bddba7ea63563c876f630088e/packages/app-builder-lib/src/publish/PublishManager.ts#L74-L92

**Comment by XurxoMF** [comment]
This is still a problem. My GH Action failed because it tried to publish... I've auto updated with GitHub so i don't know if I can use --publish=never or if that will break auto updates...

**Comment by nandenjin** [comment]
I think it is still a live problem and I support this proposal. It's been nearly five years since this issue was opened, and I'd like to hear what the maintainers think.
