### ISSUE TITLE
Warn while building (electron-builder from 26.0.19 to 26.3.1), why?

### ISSUE THREAD

**Issue by lk101** [electron-userland/electron-builder#9393]
There is the output of PowerShell 7 after I run `electron-builder`.

At 26.0.19, there was no error like "Failed to read package.json for .: Cannot find module 'package.json'". After I upgraded the electron-builder version to 26.3.1, these errors appeared, but they don’t seem to affect the generation of my installation package. Does this error message really have no impact at all? Is there anything I need to adjust in my project?

```console
  • electron-builder  version=26.3.1 os=10.0.26200
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • executing @electron/rebuild  electronVersion=39.2.4 arch=x64 buildFromSource=false workspaceRoot=my-workspace projectDir=./ appDir=./
  • installing native dependencies  arch=x64
  • preparing       moduleName=sqlite3 arch=x64
  • finished        moduleName=sqlite3 arch=x64
  • completed installing native dependencies
  • packaging       platform=win32 arch=x64 electron=39.2.4 appOutDir=dist\win-unpacked
  • Failed to read package.json for .: Cannot find module 'package.json'
Require stack:
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\nodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\npmNodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\index.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\util\yarn.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\out\cli\cli.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\cli.js
  • Failed to read package.json for .: Cannot find module 'package.json'
Require stack:
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\nodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\npmNodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\index.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\util\yarn.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\out\cli\cli.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\cli.js
  • Failed to read package.json for .: Cannot find module 'package.json'
Require stack:
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\nodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\npmNodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\index.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\util\yarn.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\out\cli\cli.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\cli.js
  • Failed to read package.json for .: Cannot find module 'package.json'
Require stack:
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\nodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\npmNodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\index.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\util\yarn.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\out\cli\cli.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\cli.js
  • Failed to read package.json for .: Cannot find module 'package.json'
Require stack:
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\nodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\npmNodeModulesCollector.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\node-module-collector\index.js
- my-workspace\node_modules\.pnpm\app-builder-lib@26.3.1_dmg-_39246b0da57a745fedffa08e948e3885\node_modules\app-builder-lib\out\util\yarn.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\out\cli\cli.js
- my-workspace\node_modules\.pnpm\electron-builder@26.3.1_ele_f806ae1b70ce69e08dd4f3261416391f\node_modules\electron-builder\cli.js
  • updating asar integrity executable resource  executablePath=dist\win-unpacked\my-app.exe
  • signing with signtool.exe  path=dist\win-unpacked\other.exe
...
```

**Comment by mmaietta** [comment]
Can you try `.2`? I piped in a fix into 26.3.1/2 and have another node collector fix going into 23.6.3 - waiting on CI builds to finish on it.
The tweaks in the module collectors were made to support corepack to properly add unit tests for different package managers using common test fixtures

**Comment by lk101** [comment]
> Can you try `.2`? I piped in a fix into 26.3.1/2 and have another node collector fix going into 23.6.3 - waiting on CI builds to finish on it. The tweaks in the module collectors were made to support corepack to properly add unit tests for different package managers using common test fixtures

OK，I'll try it. Thanks a lot.

**Comment by lk101** [comment]
> Can you try `.2`? I piped in a fix into 26.3.1/2 and have another node collector fix going into 23.6.3 - waiting on CI builds to finish on it. The tweaks in the module collectors were made to support corepack to properly add unit tests for different package managers using common test fixtures

Excellent! Version 26.3.2 has resolved this issue. Thank you very much for your help.
