### ISSUE TITLE
v24.x.x: Legacy dependency shadows compilation error on Yarn

### ISSUE THREAD

**Issue by SuibianP** [electron-userland/electron-builder#8942]
*Note: This issue does not affect v25 onwards. I chose to open this issue as v24 continues to be of some relevance per npm download stats. Please feel free to close if no fixes are to be made on past major versions. Regardlessly, I am interested in the root cause and possible workarounds.*

I have a package that **should** fail to compile on Electron 34.3.0, as demonstrated by trying to install the `package.json` MRE below:

```json
{
  "name": "test-detect-dep",
  "version": "1.0.0",
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "dist": "electron-builder",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@abandonware/bluetooth-hci-socket": "^0.5.3-8", <== without this line
    "serialport": "13.0.0"
  },
  "devDependencies": {
    "electron": "34.3.0",
    "electron-builder": "^24.4.0",
    "node-gyp": "^9.4.0"
  },
  "build": {
    "buildDependenciesFromSource": true,
    "nodeGypRebuild": false
  },
  "packageManager": "yarn@4.7.0"
}
```

The issue manifests itself when adding `"@abandonware/bluetooth-hci-socket": "^0.5.3-8"` into the dependencies. After this addition, `install-app-deps` still fails the compilation as expected under npm, but incorrectly reports success under yarn without actually building the artifact.

I understand that the added dependency is legacy and still using `node-pre-gyp`, but it really should not be changing behaviour or silencing errors in other packages.

Versions: node 23.8.0; npm 10.9.2, yarn 4.7.0 (with `nodeLinker: node-modules` set); electron-builder 24.13.3

**Comment by mmaietta** [comment]
Great to hear that it's resolved in v25 onwards. Going to close this as Complete then as there's nothing I can do for v24, nor really support due to the way the CI is configured, but thanks for opening the issue to bring awareness to others that may encounter the same issue.
